version: '3.8'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:11'
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/dbdata/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=testdb
