version: "3.8"

services:
  postgres:
    container_name: "postgres"
    image: "postgres:11"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/dbdata/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=testdb

  app:
    image: golang:1.19
    ports:
      - "8080:8080"
    env_file:
      - env.list
    volumes:
      - \$PWD:/go/src/app
    working_dir: /go/src/app
    depends_on:
      - postgres
    command: bash -c "make run"
