---
engines:
  revive: 
    exclude_paths:
    - ".bundle/**"
    - "spec/**/*"
    - "benchmarks/**/*"
    - "**.min.js"
    - "**/tests/**"
    - "**/test/**"
    - "**factory.go"
    - "**enumer.go"
    - "**fielder.go"
    - "**.md"
    - "**_test.go"
    - "**/mocks/**"
    - "**/testdata/**"
    - "test/**/*"
    - "**.sql"
    - "**.yml"
    - "**.yaml"
    - "**_mock.go"
    - ".github/**"
    - "**tools/**"
    - "**api/**"
    - "**Dockerfile"
    - "**Makefile"
    - "**vendor/**"
    - "**scripts/**"
    - "**db/**"
    - "**main.go"
    - "**configs/**"
    config:
      languages:
        - "go"
  duplication:
    exclude_paths:
      - ".bundle/**"
      - "spec/**/*"
      - "benchmarks/**/*"
      - "**.min.js"
      - "**/tests/**"
      - "**/test/**"
      - "**factory.go"
      - "**enumer.go"
      - "**fielder.go"
      - "**.md"
      - "**_test.go"
      - "**/mocks/**"
      - "**/testdata/**"
      - "test/**/*"
      - "**.sql"
      - "**.yml"
      - "**.yaml"
      - "**_mock.go"
      - ".github/**"
      - "**tools/**"
      - "**api/**"
      - "**Dockerfile"
      - "**Makefile"
      - "**vendor/**"
      - "**scripts/**"
      - "**db/**"
      - "**main.go"
      - "**configs/**"

exclude_paths:
  - ".bundle/**"
  - "spec/**/*"
  - "benchmarks/**/*"
  - "**.min.js"
  - "**/tests/**"
  - "**/test/**"
  - "**factory.go"
  - "**enumer.go"
  - "**fielder.go"
  - "**.md"
  - "**_test.go"
  - "**/mocks/**"
  - "**/testdata/**"
  - "test/**/*"
  - "**.sql"
  - "**.yml"
  - "**.yaml"
  - "**_mock.go"
  - ".github/**"
  - "**tools/**"
  - "**api/**"
  - "**Dockerfile"
  - "**Makefile"
  - "**vendor/**"
  - "**scripts/**"
  - "**db/**"
  - "**main.go"
  - "**configs/**"
