{{- if .Values.kafkaTopic.enabled }}
{{- range .Values.kafkaTopic.topics }}
---
apiVersion: kafka.gympass.com/v1alpha1
kind: KafkaTopic
metadata:
  name: {{ .name }}
spec:
  {{- if .replicas }}
  replicas: {{ .replicas }}
  {{- end }}
  partitions: {{ .partitions }}
  {{- if .config }}
  config:
    {{- range \$key, \$value := .config }}
    {{ \$key }}: "{{ \$value }}"
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
